# ~/.config/hypr/hyprpaper.conf
# Updated for Hyprpaper 0.8+ block syntax

preload = ~/.config/hypr/wallpapers/astronaut2.png

wallpaper {
    monitor =
    path = ~/.config/hypr/wallpapers/astronaut2.png
}