# ~/.config/hypr/hyprland.conf
source = ~/.config/hypr/themes/current.conf  # Only ONE theme source

# ===== SAFE MODE SWITCH =====
$SAFE = 0

# 1. Programs & Variables
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/env.conf

# 2. Hardware
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf

# 3. Logic
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/animations.conf

source = ~/.config/hypr/settings.conf
# Swaync transparent background fix


# Swaync transparency fix
layerrule = ignorealpha 0.5, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center

