# Starship Catppuccin Mocha Theme
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#89b4fa)\
$os\
$username\
[](bg:#cba6f7 fg:#89b4fa)\
$directory\
[](fg:#cba6f7 bg:#f38ba8)\
$git_branch\
$git_status\
[](fg:#f38ba8 bg:#a6e3a1)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#a6e3a1 bg:#94e2d5)\
$docker_context\
[](fg:#94e2d5 bg:#1e1e2e)\
$time\
[ ](fg:#1e1e2e)\
"""

[username]
show_always = true
style_user = "bg:#89b4fa fg:#1e1e2e"
style_root = "bg:#89b4fa fg:#1e1e2e"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#89b4fa"
disabled = true

[directory]
style = "bg:#cba6f7 fg:#1e1e2e"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#94e2d5 fg:#1e1e2e"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#f38ba8 fg:#1e1e2e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#f38ba8 fg:#1e1e2e"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#a6e3a1 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#1e1e2e fg:#cdd6f4"
format = '[ ♥ $time ]($style)'
