# Starship Dracula Theme - Minimal
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$directory$character"""
palette = "dracula"
right_format = """$all"""
command_timeout = 1000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[➜](bold green)'

[directory]
style = "bold purple"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold pink"

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "bold red"

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold cyan'
symbol = " "

[golang]
format = '[$symbol($version)]($style) '
style = "bold cyan"
symbol = " "

[nodejs]
format = '[$symbol($version)]($style) '
style = "bold green"
symbol = " "

[rust]
format = '[$symbol($version)]($style) '
style = "bold orange"
symbol = " "

[python]
format = '[$symbol($version)]($style) '
style = "bold yellow"
symbol = " "

[docker_context]
disabled = true

[kubernetes]
symbol = '☸ '
disabled = true

[time]
disabled = false
time_format = "%R"
style = "bold foreground"
format = '[$time]($style)'

[palettes.dracula]
background = "#282a36"
foreground = "#f8f8f2"
selection = "#44475a"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
