# Starship Gruvbox Theme - Minimal
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$directory$character"""
palette = "gruvbox"
right_format = """$all"""
command_timeout = 1000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[➜](bold green)'

[directory]
style = "bold purple"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold aqua"

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "bold red"

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = " "

[golang]
format = '[$symbol($version)]($style) '
style = "bold aqua"
symbol = " "

[nodejs]
format = '[$symbol($version)]($style) '
style = "bold green"
symbol = " "

[rust]
format = '[$symbol($version)]($style) '
style = "bold orange"
symbol = " "

[python]
format = '[$symbol($version)]($style) '
style = "bold yellow"
symbol = " "

[docker_context]
disabled = true

[kubernetes]
symbol = '☸ '
disabled = true

[time]
disabled = false
time_format = "%R"
style = "bold foreground"
format = '[$time]($style)'

[palettes.gruvbox]
background = "#282828"
foreground = "#ebdbb2"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
purple = "#d3869b"
aqua = "#8ec07c"
orange = "#fe8019"
gray = "#928374"
