# Starship Nord Theme - Minimal
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$directory$character"""
palette = "nord"
right_format = """$all"""
command_timeout = 1000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[➜](bold green)'

[directory]
style = "bold frost_blue"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold frost_cyan"

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "bold red"

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold frost_blue'
symbol = " "

[golang]
format = '[$symbol($version)]($style) '
style = "bold frost_cyan"
symbol = " "

[nodejs]
format = '[$symbol($version)]($style) '
style = "bold green"
symbol = " "

[rust]
format = '[$symbol($version)]($style) '
style = "bold orange"
symbol = " "

[python]
format = '[$symbol($version)]($style) '
style = "bold yellow"
symbol = " "

[docker_context]
disabled = true

[kubernetes]
symbol = '☸ '
disabled = true

[time]
disabled = false
time_format = "%R"
style = "bold snow_storm"
format = '[$time]($style)'

[palettes.nord]
# Polar Night
nord0 = "#2e3440"
nord1 = "#3b4252"
nord2 = "#434c5e"
nord3 = "#4c566a"
# Snow Storm
snow_storm = "#eceff4"
nord5 = "#e5e9f0"
nord6 = "#d8dee9"
# Frost
frost_cyan = "#88c0d0"
frost_blue = "#81a1c1"
frost_blue_bright = "#5e81ac"
frost_teal = "#8fbcbb"
# Aurora
red = "#bf616a"
orange = "#d08770"
yellow = "#ebcb8b"
green = "#a3be8c"
purple = "#b48ead"
