# Starship OLED Dark Theme
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#00ff00)\
$os\
$username\
[](bg:#00ffff fg:#00ff00)\
$directory\
[](fg:#00ffff bg:#ff00ff)\
$git_branch\
$git_status\
[](fg:#ff00ff bg:#ffff00)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#ffff00 bg:#00ffcc)\
$docker_context\
[](fg:#00ffcc bg:#000000)\
$time\
[ ](fg:#000000)\
"""

[username]
show_always = true
style_user = "bg:#00ff00 fg:#000000"
style_root = "bg:#00ff00 fg:#000000"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#00ff00"
disabled = true

[directory]
style = "bg:#00ffff fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#00ffcc fg:#000000"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#ff00ff fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ff00ff fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#ffff00 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#000000 fg:#00ff00"
format = '[ ♥ $time ]($style)'
